#!/bin/bash 

files=$(ls S-m[0-9]*-[0-9][0-9][0-9][0-9]-[0-9][0-9]*.json)
for file in $files ; do
    echo $file
    sed "s/[0-9]*\.[0-9][0-9][0-9]/1.000/g" "$file" >/tmp/whiz  && mv /tmp/whiz  "$file"
done;


